[package]
name = "agni-riftbound-plugin"
version = "0.8.1"
edition = "2021"

[dependencies]
agni-plugin-sdk = { git = "https://github.com/abysl/agni" }
agni-riftbound-turns = { path = "../../games/riftbound-turns" }

[build-dependencies]
agni-riftbound = { path = "../../games/riftbound" }
agni-sim = { git = "https://github.com/abysl/agni" }

[dev-dependencies]
agni-core = { git = "https://github.com/abysl/agni" }
agni-riftbound = { path = "../../games/riftbound" }
agni-sim = { git = "https://github.com/abysl/agni" }
serde_bytes = "0.11"

[lib]
name = "riftbound_plugin"
crate-type = ["cdylib", "rlib"]
